### ISSUE TITLE
Valid offsets are not accepted

### ISSUE THREAD

**Issue by saintmac** [cisco-ie/webex-time-zones#4]
Even the example from the documentation is not accepted: '11:00'
I think the error is on that line:
`const isValidOffset = serializedOffset.match(/\d{1,2}:[0|3]0/).length > 1;`
It should be
`const isValidOffset = serializedOffset.match(/\d{1,2}:[0|3]0/).length > 0;`

**Comment by brh55** [comment]
Odd that test are still passing, but you are right that should work for the correct offset.
