### ISSUE TITLE
Does not work with summer time

### ISSUE THREAD

**Issue by saintmac** [cisco-ie/webex-time-zones#6]
If you use it in Paris in the summer, it will tell you that you are in Bucharest (1h ahead). This is because the library doesn't take into account daylight saving times

**Comment by brh55** [comment]
You are correct it doesn't work for places that do fall in DST. This is more so an approximation, but if you already know your local time zone and date+time, webex has a `fallInDST` attribute that will check the time and the specified time zone to see if it needs to account for the DST.

**Comment by saintmac** [comment]
Yes, but then this library fails in helping know what the webex timezone id is from a standard timezone, which I believe is its purpose. I ended up implementing it myself.
